"""
HTML Report Generator for CI Health Analytics.

Generates comprehensive HTML reports with visualizations
of CI health metrics, failure trends, and platform breakdowns.
"""

from datetime import datetime
from typing import Dict, List, Optional


class HTMLReportGenerator:
    """Generates HTML reports for CI health analytics."""

    def __init__(self):
        """Initialize the HTML report generator."""
        pass

    def generate_health_report(
        self,
        summary: Dict,
        platform_breakdown: Dict,
        trends: List[Dict],
        flaky_tests: List[Dict],
        slowest_jobs: List[Dict],
        output_path: str,
    ) -> str:
        """
        Generate comprehensive CI health HTML report.

        Args:
            summary: Overall health summary
            platform_breakdown: Platform-specific metrics
            trends: Daily failure trends
            flaky_tests: List of flaky tests
            slowest_jobs: List of slowest jobs
            output_path: Path to save HTML file

        Returns:
            Path to generated HTML file
        """
        html = self._generate_html(
            summary, platform_breakdown, trends, flaky_tests, slowest_jobs
        )

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        return output_path

    def _generate_html(
        self,
        summary: Dict,
        platform_breakdown: Dict,
        trends: List[Dict],
        flaky_tests: List[Dict],
        slowest_jobs: List[Dict],
    ) -> str:
        """Generate the complete HTML document."""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CI Health Report - {datetime.now().strftime("%Y-%m-%d")}</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🔍 CI Health Report</h1>
            <p class="subtitle">Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
            <p class="time-window">{summary.get('time_window', 'N/A')}</p>
        </header>

        {self._generate_summary_section(summary)}
        {self._generate_platform_section(platform_breakdown)}
        {self._generate_trends_section(trends)}
        {self._generate_flaky_tests_section(flaky_tests)}
        {self._generate_slow_jobs_section(slowest_jobs)}

        <footer>
            <p>Generated by Lens CI Analytics</p>
        </footer>
    </div>
</body>
</html>"""

    def _get_css(self) -> str:
        """Get CSS styles for the report."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 3px solid #4CAF50;
        }

        h1 {
            color: #2c3e50;
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        h2 {
            color: #34495e;
            margin: 30px 0 15px 0;
            padding-bottom: 10px;
            border-bottom: 2px solid #ecf0f1;
        }

        .subtitle {
            color: #7f8c8d;
            font-size: 0.9em;
        }

        .time-window {
            color: #3498db;
            font-weight: bold;
            margin-top: 10px;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }

        .metric-card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }

        .metric-card.success {
            background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
        }

        .metric-card.warning {
            background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
        }

        .metric-card.info {
            background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
        }

        .metric-value {
            font-size: 2.5em;
            font-weight: bold;
            margin: 10px 0;
        }

        .metric-label {
            font-size: 0.9em;
            opacity: 0.9;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ecf0f1;
        }

        th {
            background: #34495e;
            color: white;
            font-weight: 600;
        }

        tr:hover {
            background: #f8f9fa;
        }

        .status-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: bold;
        }

        .status-success {
            background: #d4edda;
            color: #155724;
        }

        .status-failure {
            background: #f8d7da;
            color: #721c24;
        }

        .status-flaky {
            background: #fff3cd;
            color: #856404;
        }

        .progress-bar {
            width: 100%;
            height: 20px;
            background: #ecf0f1;
            border-radius: 10px;
            overflow: hidden;
        }

        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #11998e 0%, #38ef7d 100%);
            transition: width 0.3s ease;
        }

        .progress-fill.low {
            background: linear-gradient(90deg, #f093fb 0%, #f5576c 100%);
        }

        .platform-stats {
            margin: 20px 0;
        }

        .platform-item {
            margin: 15px 0;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 5px;
        }

        .platform-name {
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 8px;
        }

        .chart-container {
            margin: 20px 0;
            padding: 20px;
            background: #f8f9fa;
            border-radius: 5px;
        }

        footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #ecf0f1;
            text-align: center;
            color: #7f8c8d;
            font-size: 0.9em;
        }

        .empty-state {
            text-align: center;
            padding: 40px;
            color: #95a5a6;
        }
        """

    def _generate_summary_section(self, summary: Dict) -> str:
        """Generate the summary section."""
        success_rate = summary.get("success_rate", 0)
        card_class = "success" if success_rate >= 80 else "warning"

        avg_duration_min = summary.get("avg_duration_seconds", 0) / 60

        return f"""
        <section>
            <h2>📊 Overall Health</h2>
            <div class="metrics-grid">
                <div class="metric-card info">
                    <div class="metric-label">Total Runs</div>
                    <div class="metric-value">{summary.get('total_runs', 0)}</div>
                </div>
                <div class="metric-card success">
                    <div class="metric-label">Successful</div>
                    <div class="metric-value">{summary.get('successful_runs', 0)}</div>
                </div>
                <div class="metric-card warning">
                    <div class="metric-label">Failed</div>
                    <div class="metric-value">{summary.get('failed_runs', 0)}</div>
                </div>
                <div class="metric-card {card_class}">
                    <div class="metric-label">Success Rate</div>
                    <div class="metric-value">{success_rate:.1f}%</div>
                </div>
                <div class="metric-card info">
                    <div class="metric-label">Avg Duration</div>
                    <div class="metric-value">{avg_duration_min:.1f}m</div>
                </div>
            </div>
        </section>
        """

    def _generate_platform_section(self, platform_breakdown: Dict) -> str:
        """Generate the platform breakdown section."""
        if not platform_breakdown:
            return '<section><h2>🖥️ Platform Breakdown</h2><div class="empty-state">No platform data available</div></section>'

        items_html = ""
        for platform, stats in sorted(platform_breakdown.items()):
            success_rate = stats.get("success_rate", 0)
            progress_class = "" if success_rate >= 80 else "low"

            items_html += f"""
            <div class="platform-item">
                <div class="platform-name">🖥️ {platform}</div>
                <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin: 10px 0;">
                    <div><strong>Jobs:</strong> {stats.get('total_jobs', 0)}</div>
                    <div><strong>Success:</strong> {stats.get('successful_jobs', 0)}</div>
                    <div><strong>Failed:</strong> {stats.get('failed_jobs', 0)}</div>
                    <div><strong>Avg Duration:</strong> {stats.get('avg_duration', 0):.0f}s</div>
                </div>
                <div class="progress-bar">
                    <div class="progress-fill {progress_class}" style="width: {success_rate}%;"></div>
                </div>
                <div style="text-align: right; margin-top: 5px; font-size: 0.9em; color: #7f8c8d;">
                    Success Rate: {success_rate:.1f}%
                </div>
            </div>
            """

        return f"""
        <section>
            <h2>🖥️ Platform Breakdown</h2>
            <div class="platform-stats">
                {items_html}
            </div>
        </section>
        """

    def _generate_trends_section(self, trends: List[Dict]) -> str:
        """Generate the failure trends section."""
        if not trends:
            return '<section><h2>📈 Failure Trends</h2><div class="empty-state">No trend data available</div></section>'

        rows_html = ""
        for trend in trends[-14:]:  # Last 14 days
            failure_rate = trend.get("failure_rate", 0)
            badge_class = "status-success" if failure_rate == 0 else "status-failure"

            rows_html += f"""
            <tr>
                <td>{trend.get('date', 'N/A')}</td>
                <td>{trend.get('total_runs', 0)}</td>
                <td>{trend.get('failed_runs', 0)}</td>
                <td><span class="status-badge {badge_class}">{failure_rate:.1f}%</span></td>
            </tr>
            """

        return f"""
        <section>
            <h2>📈 Failure Trends (Last 14 Days)</h2>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Total Runs</th>
                        <th>Failed Runs</th>
                        <th>Failure Rate</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
        </section>
        """

    def _generate_flaky_tests_section(self, flaky_tests: List[Dict]) -> str:
        """Generate the flaky tests section."""
        if not flaky_tests:
            return '<section><h2>⚠️ Flaky Tests</h2><div class="empty-state">✅ No flaky tests detected!</div></section>'

        rows_html = ""
        for test in flaky_tests[:20]:  # Top 20
            platforms = ", ".join(test.get("platforms", []))
            rows_html += f"""
            <tr>
                <td>{test.get('test_name', 'N/A')}</td>
                <td>{test.get('total_runs', 0)}</td>
                <td>{test.get('failures', 0)}</td>
                <td><span class="status-badge status-flaky">{test.get('failure_rate', 0):.1f}%</span></td>
                <td>{platforms}</td>
            </tr>
            """

        return f"""
        <section>
            <h2>⚠️ Flaky Tests ({len(flaky_tests)} detected)</h2>
            <table>
                <thead>
                    <tr>
                        <th>Test Name</th>
                        <th>Total Runs</th>
                        <th>Failures</th>
                        <th>Failure Rate</th>
                        <th>Platforms</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
        </section>
        """

    def _generate_slow_jobs_section(self, slowest_jobs: List[Dict]) -> str:
        """Generate the slow jobs section."""
        if not slowest_jobs:
            return '<section><h2>🐌 Slowest Jobs</h2><div class="empty-state">No job data available</div></section>'

        rows_html = ""
        for job in slowest_jobs:
            duration_min = job.get("duration_seconds", 0) / 60
            rows_html += f"""
            <tr>
                <td>{job.get('job_name', 'N/A')}</td>
                <td>{job.get('platform', 'unknown')}</td>
                <td>{duration_min:.1f}m ({job.get('duration_seconds', 0)}s)</td>
                <td>{job.get('status', 'N/A')}</td>
                <td>#{job.get('run_id', 'N/A')}</td>
            </tr>
            """

        return f"""
        <section>
            <h2>🐌 Slowest Jobs (Top {len(slowest_jobs)})</h2>
            <table>
                <thead>
                    <tr>
                        <th>Job Name</th>
                        <th>Platform</th>
                        <th>Duration</th>
                        <th>Status</th>
                        <th>Run ID</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>
        </section>
        """
