"""
HTML report generator for test execution analytics.

Generates comprehensive HTML reports with visualizations for test
execution history, flaky tests, and trends.
"""

from datetime import datetime
from typing import Dict, List


class TestExecutionReportGenerator:
    """Generator for test execution HTML reports."""

    def generate_test_summary_report(
        self,
        summary: Dict,
        flaky_tests: List[Dict],
        trends: List[Dict],
        slowest_tests: List[Dict],
        output_path: str,
    ):
        """
        Generate comprehensive test execution summary report.

        Args:
            summary: Execution summary statistics
            flaky_tests: List of flaky tests
            trends: Daily trend data
            slowest_tests: Slowest tests by duration
            output_path: Path to save HTML report
        """
        html = self._generate_html(summary, flaky_tests, trends, slowest_tests)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

    def _generate_html(
        self,
        summary: Dict,
        flaky_tests: List[Dict],
        trends: List[Dict],
        slowest_tests: List[Dict],
    ) -> str:
        """Generate the complete HTML document."""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Execution Report</title>
    <style>
        {self._get_css()}
    </style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
</head>
<body>
    <div class="container">
        <header>
            <h1>Test Execution Report</h1>
            <p class="subtitle">Generated on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </header>

        {self._generate_summary_section(summary)}
        {self._generate_trends_section(trends)}
        {self._generate_flaky_tests_section(flaky_tests)}
        {self._generate_slowest_tests_section(slowest_tests)}

        <footer>
            <p>Generated by Lens Test Execution Analytics</p>
        </footer>
    </div>

    <script>
        {self._generate_javascript(trends)}
    </script>
</body>
</html>"""

    def _get_css(self) -> str:
        """Get CSS styles for the report."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: #f5f5f5;
            color: #333;
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }

        header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .subtitle {
            opacity: 0.9;
            font-size: 1.1em;
        }

        .section {
            background: white;
            padding: 30px;
            margin-bottom: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .section h2 {
            color: #667eea;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #f0f0f0;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }

        .metric-card {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }

        .metric-card.success {
            background: linear-gradient(135deg, #f093fb 0%, #4facfe 100%);
            color: white;
        }

        .metric-card.warning {
            background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
            color: white;
        }

        .metric-card.danger {
            background: linear-gradient(135deg, #fe5858 0%, #ff6b9d 100%);
            color: white;
        }

        .metric-value {
            font-size: 2.5em;
            font-weight: bold;
            margin-bottom: 5px;
        }

        .metric-label {
            font-size: 0.9em;
            opacity: 0.9;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #f0f0f0;
        }

        th {
            background: #f8f9fa;
            font-weight: 600;
            color: #667eea;
        }

        tr:hover {
            background: #f8f9fa;
        }

        .chart-container {
            position: relative;
            height: 400px;
            margin: 30px 0;
        }

        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.85em;
            font-weight: 500;
        }

        .badge-success {
            background: #d4edda;
            color: #155724;
        }

        .badge-warning {
            background: #fff3cd;
            color: #856404;
        }

        .badge-danger {
            background: #f8d7da;
            color: #721c24;
        }

        footer {
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 0.9em;
        }

        .progress-bar {
            width: 100%;
            height: 20px;
            background: #e0e0e0;
            border-radius: 10px;
            overflow: hidden;
            margin-top: 10px;
        }

        .progress-fill {
            height: 100%;
            background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
            transition: width 0.3s ease;
        }
        """

    def _generate_summary_section(self, summary: Dict) -> str:
        """Generate summary metrics section."""
        success_rate = summary["success_rate"]
        card_class = (
            "success"
            if success_rate >= 95
            else "warning" if success_rate >= 80 else "danger"
        )

        return f"""
        <div class="section">
            <h2>Execution Summary ({summary['window_days']} days)</h2>
            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-value">{summary['total_executions']}</div>
                    <div class="metric-label">Total Executions</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{summary['unique_tests']}</div>
                    <div class="metric-label">Unique Tests</div>
                </div>
                <div class="metric-card {card_class}">
                    <div class="metric-value">{summary['success_rate']:.1f}%</div>
                    <div class="metric-label">Success Rate</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{summary['avg_duration']:.2f}s</div>
                    <div class="metric-label">Avg Duration</div>
                </div>
            </div>

            <div style="margin-top: 30px;">
                <h3>Test Results Breakdown</h3>
                <table>
                    <tr>
                        <th>Status</th>
                        <th>Count</th>
                        <th>Percentage</th>
                    </tr>
                    <tr>
                        <td><span class="badge badge-success">PASSED</span></td>
                        <td>{summary['passed']}</td>
                        <td>{summary['passed'] / summary['total_executions'] * 100 if summary['total_executions'] > 0 else 0:.1f}%</td>
                    </tr>
                    <tr>
                        <td><span class="badge badge-danger">FAILED</span></td>
                        <td>{summary['failed']}</td>
                        <td>{summary['failed'] / summary['total_executions'] * 100 if summary['total_executions'] > 0 else 0:.1f}%</td>
                    </tr>
                    <tr>
                        <td><span class="badge badge-warning">SKIPPED</span></td>
                        <td>{summary['skipped']}</td>
                        <td>{summary['skipped'] / summary['total_executions'] * 100 if summary['total_executions'] > 0 else 0:.1f}%</td>
                    </tr>
                </table>
            </div>
        </div>
        """

    def _generate_trends_section(self, trends: List[Dict]) -> str:
        """Generate trends visualization section."""
        if not trends:
            return """
            <div class="section">
                <h2>Execution Trends</h2>
                <p>No trend data available. Run tests over time to generate trends.</p>
            </div>
            """

        return """
        <div class="section">
            <h2>Execution Trends</h2>
            <div class="chart-container">
                <canvas id="trendsChart"></canvas>
            </div>
        </div>
        """

    def _generate_flaky_tests_section(self, flaky_tests: List[Dict]) -> str:
        """Generate flaky tests section."""
        if not flaky_tests:
            return """
            <div class="section">
                <h2>Flaky Tests</h2>
                <p style="color: #28a745; font-weight: 500;">✓ No flaky tests detected!</p>
            </div>
            """

        rows = ""
        for test in flaky_tests:
            # Shorten test ID for display
            entity_id = test["entity_id"]
            if len(entity_id) > 80:
                entity_id = "..." + entity_id[-77:]

            badge_class = (
                "danger"
                if test["failure_rate"] > 0.3
                else "warning" if test["failure_rate"] > 0.1 else "success"
            )

            rows += f"""
            <tr>
                <td><code>{entity_id}</code></td>
                <td>{test['total_runs']}</td>
                <td>{test['passed']}</td>
                <td>{test['failed']}</td>
                <td><span class="badge badge-{badge_class}">{test['failure_rate']*100:.1f}%</span></td>
                <td>{test['avg_duration']:.2f}s</td>
            </tr>
            """

        return f"""
        <div class="section">
            <h2>Flaky Tests ({len(flaky_tests)} detected)</h2>
            <p>Tests with inconsistent pass/fail behavior that may indicate reliability issues.</p>
            <table>
                <thead>
                    <tr>
                        <th>Test ID</th>
                        <th>Total Runs</th>
                        <th>Passed</th>
                        <th>Failed</th>
                        <th>Failure Rate</th>
                        <th>Avg Duration</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </div>
        """

    def _generate_slowest_tests_section(self, slowest_tests: List[Dict]) -> str:
        """Generate slowest tests section."""
        if not slowest_tests:
            return ""

        rows = ""
        for test in slowest_tests:
            # Shorten test ID for display
            entity_id = test["entity_id"]
            if len(entity_id) > 80:
                entity_id = "..." + entity_id[-77:]

            rows += f"""
            <tr>
                <td><code>{entity_id}</code></td>
                <td>{test['total_runs']}</td>
                <td>{test['avg_duration']:.2f}s</td>
            </tr>
            """

        return f"""
        <div class="section">
            <h2>Slowest Tests</h2>
            <p>Tests with the longest average execution time.</p>
            <table>
                <thead>
                    <tr>
                        <th>Test ID</th>
                        <th>Total Runs</th>
                        <th>Avg Duration</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </div>
        """

    def _generate_javascript(self, trends: List[Dict]) -> str:
        """Generate JavaScript for charts."""
        if not trends:
            return ""

        # Prepare data for Chart.js
        dates = [t["date"] for t in trends]
        passed = [t["passed"] for t in trends]
        failed = [t["failed"] for t in trends]
        success_rates = [t["success_rate"] for t in trends]

        return f"""
        const ctx = document.getElementById('trendsChart').getContext('2d');
        new Chart(ctx, {{
            type: 'line',
            data: {{
                labels: {dates},
                datasets: [
                    {{
                        label: 'Passed',
                        data: {passed},
                        borderColor: '#28a745',
                        backgroundColor: 'rgba(40, 167, 69, 0.1)',
                        tension: 0.3
                    }},
                    {{
                        label: 'Failed',
                        data: {failed},
                        borderColor: '#dc3545',
                        backgroundColor: 'rgba(220, 53, 69, 0.1)',
                        tension: 0.3
                    }},
                    {{
                        label: 'Success Rate (%)',
                        data: {success_rates},
                        borderColor: '#667eea',
                        backgroundColor: 'rgba(102, 126, 234, 0.1)',
                        yAxisID: 'y1',
                        tension: 0.3
                    }}
                ]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                interaction: {{
                    mode: 'index',
                    intersect: false
                }},
                plugins: {{
                    legend: {{
                        position: 'top'
                    }},
                    title: {{
                        display: true,
                        text: 'Test Execution Trends'
                    }}
                }},
                scales: {{
                    y: {{
                        type: 'linear',
                        display: true,
                        position: 'left',
                        title: {{
                            display: true,
                            text: 'Test Count'
                        }}
                    }},
                    y1: {{
                        type: 'linear',
                        display: true,
                        position: 'right',
                        title: {{
                            display: true,
                            text: 'Success Rate (%)'
                        }},
                        grid: {{
                            drawOnChartArea: false
                        }},
                        min: 0,
                        max: 100
                    }}
                }}
            }}
        }});
        """
